version: "3"

services:
  zipper:
    build:
      context: tools
      dockerfile: zip.dockerfile
    entrypoint: bash
    command: compose-build.sh
    working_dir: /src/bin
    volumes:
      - "./:/src"
    restart: "no"
