version: '3'

services:
  wp:
    # https://hub.docker.com/_/wordpress/
    # image: wordpress:6.1.1:latest
    # image: wordpress:5.6.0-php7.2
    # image: wordpress:5.9.2-php7.3
    # image: wordpress:6.1.1-php7.4
    # image: wordpress:6.1.1-php8.0
    image: wordpress:6.1.1-php8.1
    ports:
      - ${IP}:80:80 # change ip if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - wp_app:/var/www/html # Full wordpress project
      - ./yesticket/:/var/www/html/wp-content/plugins/yesticket # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      WORDPRESS_DEBUG: true
    depends_on:
      - db
    links:
      - db

  # wpcli:
  #   image: wordpress:cli
  #   volumes:
  #     - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
  #     - wp_app:/var/www/html
  #   environment:
  #     WORDPRESS_DB_HOST: db
  #     WORDPRESS_DB_NAME: "${DB_NAME}"
  #     WORDPRESS_DB_USER: root
  #     WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
  #   depends_on:
  #     - db
  #     - wp

  # pma:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
  #     PMA_HOST: db
  #     PMA_PORT: 3306
  #     MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}" #user will be 'root'
  #     UPLOAD_LIMIT: 50M
  #   ports:
  #     - ${IP}:8080:80
  #   links:
  #     - db:db

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

volumes:
  wp_app:
  db_data:
